n2cal:
    data_dir: "/mnt/gong/archive"
    acq: "20180818T013141Z_chimeN2_corr"
    output_dir: "/mnt/gong/ssiegel/test/solar"
    output_prefix: "eigen"
    bad_input_file: "/mnt/gong/ssiegel/test/solar/bad_inputs_20180820_20180831.pickle"
    niceness: 10
    downsample: 5
    freq_start: 2
    freq_stop: 3
    neigen: 32
    niter: 10
    offsets:
        - 256
    cross_pol: True
    sep_pol: False
    normalize: True